name: Contributor Helper

on:
  issues:
  workflow_dispatch:

jobs:
  contributor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions-cool/contributor-helper@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          update-files: 'README.md, README.zh-CN.md'
          update-places: 'CONTRIBUTING.md)./## 📧 Contact us, CONTRIBUTING.md)。/## 📧 联系我们'
          repo: 'antvis/G2Plot'
          style: 'simple'

      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git pull
          git add -A
          git commit -m "🤖 Auto update contributors" || exit 0
          git push
