name: Test Context

on:
  issues:
  pull_request:
  release:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/test-ci@main
        with:
          a: ${{ secrets.TOKEN1 }} ${{ secrets.TOKEN2 }}
